# -*- encoding: utf-8 -*-

=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

Generated by: OpenAPI Generator (https://openapi-generator.tech)

=end

$:.push File.expand_path("../lib", __FILE__)
require "ynab/version"

Gem::Specification.new do |s|
  s.name        = "ynab"
  s.version     = YNAB::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["YNAB"]
  s.email       = ["api@ynab.com"]
  s.homepage    = "https://github.com/ynab/ynab-sdk-ruby"
  s.summary     = "YNAB API Client for Ruby"
  s.description = "Ruby gem wrapper for the YNAB API. API documentation available at https://api.ynab.com. Generated from server specification version 1.72.0 using OpenAPI Generator version 7.7.0."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 3.3"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
