=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CategoriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoriesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoriesApi' do
    it 'should create an instance of CategoriesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CategoriesApi)
    end
  end

  # unit tests for get_categories
  # List categories
  # Returns all categories grouped by category group
  # @param budget_id ID of budget
  # @param [Hash] opts the optional parameters
  # @return [CategoriesResponse]
  describe 'get_categories test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_category_by_id
  # Single category
  # Returns a single category
  # @param budget_id ID of budget
  # @param category_id ID of category
  # @param [Hash] opts the optional parameters
  # @return [CategoryResponse]
  describe 'get_category_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
