=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MonthsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MonthsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MonthsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MonthsApi' do
    it 'should create an instance of MonthsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MonthsApi)
    end
  end

  # unit tests for get_budget_month
  # Single budget month
  # Returns a single budget month
  # @param budget_id ID of budget
  # @param month The budget month.  \&quot;current\&quot; can also be used to specify the current calendar month (UTC).
  # @param [Hash] opts the optional parameters
  # @return [MonthDetailResponse]
  describe 'get_budget_month test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_budget_months
  # List budget months
  # Returns all budget months
  # @param budget_id ID of budget
  # @param [Hash] opts the optional parameters
  # @return [MonthSummariesResponse]
  describe 'get_budget_months test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
