=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PayeesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PayeesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PayeesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayeesApi' do
    it 'should create an instance of PayeesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PayeesApi)
    end
  end

  # unit tests for get_payee_by_id
  # Single payee
  # Returns single payee
  # @param budget_id ID of budget
  # @param payee_id ID of payee
  # @param [Hash] opts the optional parameters
  # @return [PayeeResponse]
  describe 'get_payee_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payees
  # List payees
  # Returns all payees
  # @param budget_id ID of budget
  # @param [Hash] opts the optional parameters
  # @return [PayeesResponse]
  describe 'get_payees test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
