=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TransactionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionsApi' do
    it 'should create an instance of TransactionsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TransactionsApi)
    end
  end

  # unit tests for get_transactions
  # List transactions
  # Returns all budget transactions
  # @param budget_id ID of budget
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :since_date Only return transactions on or after this date
  # @return [TransactionSummariesResponse]
  describe 'get_transactions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transactions_by_account
  # List account transactions
  # Returns all transactions for a specified account
  # @param budget_id ID of budget
  # @param account_id ID of account
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :since_date Only return transactions on or after this date
  # @return [TransactionSummariesResponse]
  describe 'get_transactions_by_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transactions_by_category
  # List category transactions
  # Returns all transactions for a specified category
  # @param budget_id ID of budget
  # @param category_id ID of category
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :since_date Only return transactions on or after this date
  # @return [TransactionSummariesResponse]
  describe 'get_transactions_by_category test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transactions_by_id
  # Single transaction
  # Returns a single transaction
  # @param budget_id ID of budget
  # @param transaction_id ID of transaction
  # @param [Hash] opts the optional parameters
  # @return [TransactionDetailResponse]
  describe 'get_transactions_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
