=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account'
require 'swagger_client/models/account_response'
require 'swagger_client/models/account_wrapper'
require 'swagger_client/models/accounts_response'
require 'swagger_client/models/accounts_wrapper'
require 'swagger_client/models/budget_detail_response'
require 'swagger_client/models/budget_detail_wrapper'
require 'swagger_client/models/budget_summary'
require 'swagger_client/models/budget_summary_response'
require 'swagger_client/models/budget_summary_wrapper'
require 'swagger_client/models/categories_response'
require 'swagger_client/models/category'
require 'swagger_client/models/category_group'
require 'swagger_client/models/category_groups_wrapper'
require 'swagger_client/models/category_response'
require 'swagger_client/models/category_wrapper'
require 'swagger_client/models/currency_format'
require 'swagger_client/models/date_format'
require 'swagger_client/models/error_detail'
require 'swagger_client/models/error_response'
require 'swagger_client/models/month_detail_response'
require 'swagger_client/models/month_detail_wrapper'
require 'swagger_client/models/month_summaries_response'
require 'swagger_client/models/month_summaries_wrapper'
require 'swagger_client/models/month_summary'
require 'swagger_client/models/payee'
require 'swagger_client/models/payee_location'
require 'swagger_client/models/payee_location_response'
require 'swagger_client/models/payee_location_wrapper'
require 'swagger_client/models/payee_locations_response'
require 'swagger_client/models/payee_locations_wrapper'
require 'swagger_client/models/payee_response'
require 'swagger_client/models/payee_wrapper'
require 'swagger_client/models/payees_response'
require 'swagger_client/models/payees_wrapper'
require 'swagger_client/models/scheduled_sub_transaction'
require 'swagger_client/models/scheduled_transaction_detail_response'
require 'swagger_client/models/scheduled_transaction_detail_wrapper'
require 'swagger_client/models/scheduled_transaction_summaries_response'
require 'swagger_client/models/scheduled_transaction_summaries_wrapper'
require 'swagger_client/models/scheduled_transaction_summary'
require 'swagger_client/models/sub_transaction'
require 'swagger_client/models/transaction_detail_response'
require 'swagger_client/models/transaction_detail_wrapper'
require 'swagger_client/models/transaction_summaries_response'
require 'swagger_client/models/transaction_summaries_wrapper'
require 'swagger_client/models/transaction_summary'
require 'swagger_client/models/budget_detail'
require 'swagger_client/models/category_group_with_categories'
require 'swagger_client/models/month_detail'
require 'swagger_client/models/scheduled_transaction_detail'
require 'swagger_client/models/transaction_detail'

# APIs
require 'swagger_client/api/accounts_api'
require 'swagger_client/api/budgets_api'
require 'swagger_client/api/categories_api'
require 'swagger_client/api/months_api'
require 'swagger_client/api/payee_locations_api'
require 'swagger_client/api/payees_api'
require 'swagger_client/api/scheduled_transactions_api'
require 'swagger_client/api/transactions_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
