=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module YNAB
  class AccountType
    
    CHECKING = 'checking'.freeze
    SAVINGS = 'savings'.freeze
    CASH = 'cash'.freeze
    CREDIT_CARD = 'creditCard'.freeze
    LINE_OF_CREDIT = 'lineOfCredit'.freeze
    OTHER_ASSET = 'otherAsset'.freeze
    OTHER_LIABILITY = 'otherLiability'.freeze
    MORTGAGE = 'mortgage'.freeze
    AUTO_LOAN = 'autoLoan'.freeze
    STUDENT_LOAN = 'studentLoan'.freeze
    PERSONAL_LOAN = 'personalLoan'.freeze
    MEDICAL_DEBT = 'medicalDebt'.freeze
    OTHER_DEBT = 'otherDebt'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AccountType.constants.select { |c| AccountType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AccountType" if constantValues.empty?
      value
    end
  end
end
