=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

Generated by: OpenAPI Generator (https://openapi-generator.tech)

=end

require 'date'
require 'time'

module YNAB
  class MonthDetail < ApiModelBase
    attr_accessor :month

    attr_accessor :note

    # The total amount of transactions categorized to 'Inflow: Ready to Assign' in the month
    attr_accessor :income

    # The total amount assigned (budgeted) in the month
    attr_accessor :budgeted

    # The total amount of transactions in the month, excluding those categorized to 'Inflow: Ready to Assign'
    attr_accessor :activity

    # The available amount for 'Ready to Assign'
    attr_accessor :to_be_budgeted

    # The Age of Money as of the month
    attr_accessor :age_of_money

    # Whether or not the month has been deleted.  Deleted months will only be included in delta requests.
    attr_accessor :deleted

    # The total income formatted in the plan's currency format
    attr_accessor :income_formatted

    # The total income as a decimal currency amount
    attr_accessor :income_currency

    # The total amount assigned formatted in the plan's currency format
    attr_accessor :budgeted_formatted

    # The total amount assigned as a decimal currency amount
    attr_accessor :budgeted_currency

    # The total activity amount formatted in the plan's currency format
    attr_accessor :activity_formatted

    # The total activity amount as a decimal currency amount
    attr_accessor :activity_currency

    # The available amount for 'Ready to Assign' formatted in the plan's currency format
    attr_accessor :to_be_budgeted_formatted

    # The available amount for 'Ready to Assign' as a decimal currency amount
    attr_accessor :to_be_budgeted_currency

    # The plan month categories.  Amounts (budgeted, activity, balance, etc.) are specific to the {month} parameter specified.
    attr_accessor :categories

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'month' => :'month',
        :'note' => :'note',
        :'income' => :'income',
        :'budgeted' => :'budgeted',
        :'activity' => :'activity',
        :'to_be_budgeted' => :'to_be_budgeted',
        :'age_of_money' => :'age_of_money',
        :'deleted' => :'deleted',
        :'income_formatted' => :'income_formatted',
        :'income_currency' => :'income_currency',
        :'budgeted_formatted' => :'budgeted_formatted',
        :'budgeted_currency' => :'budgeted_currency',
        :'activity_formatted' => :'activity_formatted',
        :'activity_currency' => :'activity_currency',
        :'to_be_budgeted_formatted' => :'to_be_budgeted_formatted',
        :'to_be_budgeted_currency' => :'to_be_budgeted_currency',
        :'categories' => :'categories'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'month' => :'Date',
        :'note' => :'String',
        :'income' => :'Integer',
        :'budgeted' => :'Integer',
        :'activity' => :'Integer',
        :'to_be_budgeted' => :'Integer',
        :'age_of_money' => :'Integer',
        :'deleted' => :'Boolean',
        :'income_formatted' => :'String',
        :'income_currency' => :'Float',
        :'budgeted_formatted' => :'String',
        :'budgeted_currency' => :'Float',
        :'activity_formatted' => :'String',
        :'activity_currency' => :'Float',
        :'to_be_budgeted_formatted' => :'String',
        :'to_be_budgeted_currency' => :'Float',
        :'categories' => :'Array<Category>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'MonthSummary'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `YNAB::MonthDetail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `YNAB::MonthDetail`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'month')
        self.month = attributes[:'month']
      end

      if attributes.key?(:'note')
        self.note = attributes[:'note']
      end

      if attributes.key?(:'income')
        self.income = attributes[:'income']
      end

      if attributes.key?(:'budgeted')
        self.budgeted = attributes[:'budgeted']
      end

      if attributes.key?(:'activity')
        self.activity = attributes[:'activity']
      end

      if attributes.key?(:'to_be_budgeted')
        self.to_be_budgeted = attributes[:'to_be_budgeted']
      end

      if attributes.key?(:'age_of_money')
        self.age_of_money = attributes[:'age_of_money']
      end

      if attributes.key?(:'deleted')
        self.deleted = attributes[:'deleted']
      end

      if attributes.key?(:'income_formatted')
        self.income_formatted = attributes[:'income_formatted']
      end

      if attributes.key?(:'income_currency')
        self.income_currency = attributes[:'income_currency']
      end

      if attributes.key?(:'budgeted_formatted')
        self.budgeted_formatted = attributes[:'budgeted_formatted']
      end

      if attributes.key?(:'budgeted_currency')
        self.budgeted_currency = attributes[:'budgeted_currency']
      end

      if attributes.key?(:'activity_formatted')
        self.activity_formatted = attributes[:'activity_formatted']
      end

      if attributes.key?(:'activity_currency')
        self.activity_currency = attributes[:'activity_currency']
      end

      if attributes.key?(:'to_be_budgeted_formatted')
        self.to_be_budgeted_formatted = attributes[:'to_be_budgeted_formatted']
      end

      if attributes.key?(:'to_be_budgeted_currency')
        self.to_be_budgeted_currency = attributes[:'to_be_budgeted_currency']
      end

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @month.nil?
      return false if @income.nil?
      return false if @budgeted.nil?
      return false if @activity.nil?
      return false if @to_be_budgeted.nil?
      return false if @deleted.nil?
      return false if @categories.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          month == o.month &&
          note == o.note &&
          income == o.income &&
          budgeted == o.budgeted &&
          activity == o.activity &&
          to_be_budgeted == o.to_be_budgeted &&
          age_of_money == o.age_of_money &&
          deleted == o.deleted &&
          income_formatted == o.income_formatted &&
          income_currency == o.income_currency &&
          budgeted_formatted == o.budgeted_formatted &&
          budgeted_currency == o.budgeted_currency &&
          activity_formatted == o.activity_formatted &&
          activity_currency == o.activity_currency &&
          to_be_budgeted_formatted == o.to_be_budgeted_formatted &&
          to_be_budgeted_currency == o.to_be_budgeted_currency &&
          categories == o.categories
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [month, note, income, budgeted, activity, to_be_budgeted, age_of_money, deleted, income_formatted, income_currency, budgeted_formatted, budgeted_currency, activity_formatted, activity_currency, to_be_budgeted_formatted, to_be_budgeted_currency, categories].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end

end
