=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

Generated by: OpenAPI Generator (https://openapi-generator.tech)

=end

require 'date'
require 'time'

module YNAB
  class ScheduledTransactionFrequency
    NEVER = "never".freeze
    DAILY = "daily".freeze
    WEEKLY = "weekly".freeze
    EVERY_OTHER_WEEK = "everyOtherWeek".freeze
    TWICE_A_MONTH = "twiceAMonth".freeze
    EVERY4_WEEKS = "every4Weeks".freeze
    MONTHLY = "monthly".freeze
    EVERY_OTHER_MONTH = "everyOtherMonth".freeze
    EVERY3_MONTHS = "every3Months".freeze
    EVERY4_MONTHS = "every4Months".freeze
    TWICE_A_YEAR = "twiceAYear".freeze
    YEARLY = "yearly".freeze
    EVERY_OTHER_YEAR = "everyOtherYear".freeze

    def self.all_vars
      @all_vars ||= [NEVER, DAILY, WEEKLY, EVERY_OTHER_WEEK, TWICE_A_MONTH, EVERY4_WEEKS, MONTHLY, EVERY_OTHER_MONTH, EVERY3_MONTHS, EVERY4_MONTHS, TWICE_A_YEAR, YEARLY, EVERY_OTHER_YEAR].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ScheduledTransactionFrequency.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ScheduledTransactionFrequency"
    end
  end
end
