=begin
#YNAB API Endpoints

#Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.70.0

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module YNAB
  class TransactionFlagColor
    RED = "red".freeze
    ORANGE = "orange".freeze
    YELLOW = "yellow".freeze
    GREEN = "green".freeze
    BLUE = "blue".freeze
    PURPLE = "purple".freeze
    NULL = "null".freeze

    def self.all_vars
      @all_vars ||= [RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, NULL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TransactionFlagColor.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TransactionFlagColor"
    end
  end
end
